### ISSUE TITLE
Update style for OMT v3.5

### ISSUE THREAD

**Issue by jirik** [klokantech/oldmapsonline-gl-style#1]
https://github.com/openmaptiles/openmaptiles/releases/tag/v3.5

**Comment by petrsloup** [comment]
After this change, the style now requires MapBox GL JS version at least 0.33.0, because we have several `maxzoom: 24`.

See https://github.com/mapbox/mapbox-gl-js/commit/b3d4460ac84e8e9f43ec88da02599d1ae7f06002
